//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lecznica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operations
    {
        public int Id { get; set; }
        public string Rodzaj_operacji { get; set; }
        public string Imie { get; set; }
        public string Imie_zwierzecia { get; set; }
        public string Opis_operacji { get; set; }
    }
}
